name: CI/CD onnxruntime arm build

on: [push]

jobs:
  build_interval_map:
    name: Build onnxruntime for arm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Checkout submodules
        run: git submodule update --init --recursive
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      - name: Cache bazel
        uses: actions/cache@v4
        env:
          cache-name: bazel-cache
        with:
          path: |
            ~/.cache/bazelisk
            ~/.cache/bazel
          key: ${{ runner.os }}-${{ env.cache-name }}
      - name: Build binary
        run: python3 bazelisk/bazelisk.py build //:onnxruntime_test --platforms=//toolchain_arm32_gcc_musl --incompatible_enable_cc_toolchain_resolution --compilation_mode=opt
